<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="11.3.18" />
    <PackageVersion Include="Avalonia.Controls.ColorPicker" Version="11.3.18" />
    <PackageVersion Include="Avalonia.Controls.DataGrid" Version="11.3.13" />
    <PackageVersion Include="Avalonia.Desktop" Version="11.3.18" />
    <PackageVersion Include="Avalonia.FuncUI" Version="1.6.0" />
    <PackageVersion Include="Avalonia.FuncUI.Elmish" Version="1.6.0" />
    <PackageVersion Include="Avalonia.Headless.XUnit" Version="11.3.18" />
    <PackageVersion Include="Avalonia.Skia" Version="11.3.18" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.3.18" />
    <PackageVersion Include="FSharp.Core" Version="6.0.0" />
    <PackageVersion Include="Verify.Avalonia" Version="1.4.0" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>
</Project>
