<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\JiraBoard.App\JiraBoard.App.fsproj" />
    <ProjectReference Include="..\..\src\JiraBoard.Ui\JiraBoard.Ui.fsproj" />
  </ItemGroup>
</Project>
